"""Build RESULTS.md from outputs/*.csv (no model fitting)."""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
O = HERE / "outputs"
P = pd.read_csv(O / "E1_primary_scores.csv").set_index("model")
NULL = pd.read_csv(O / "E1_primary_null.csv")
E3 = pd.read_csv(O / "E3_scores.csv")
A1 = pd.read_csv(O / "E1_all_scores.csv")
A2 = pd.read_csv(O / "E2_all_scores.csv")


def f(x, d=3):
    return "—" if pd.isna(x) else f"{x:.{d}f}"


# ---- null: delta R2 vs M1 per draw
nw = NULL.pivot_table(index="draw", columns="model", values="R2")
tests = []
for m in ["M2_ENR", "M3_ENR+time", "M4_mixed", "M5_SVR", "M6_SVR+time"]:
    obs = P.loc[m, "R2"] - P.loc["M1_time", "R2"]
    null = (nw[m] - nw["M1_time"]).dropna()
    obs_r = P.loc[m, "r"]
    null_r = NULL[NULL.model == m].r.dropna()
    tests.append({"model": m, "dR2_vs_time": obs, "p_dR2": (np.sum(null >= obs) + 1) / (len(null) + 1),
                  "r": obs_r, "p_r": (np.sum(null_r >= obs_r) + 1) / (len(null_r) + 1),
                  "dR2_vs_persistence": P.loc[m, "R2"] - P.loc["M0_persistence", "R2"], "n_null": len(null)})
T = pd.DataFrame(tests).set_index("model")
T.to_csv(O / "E1_primary_tests.csv")

lines = ["# DR-SCC forward chaining: results", "", "<!-- ai-start -->",
         "Generated by `summarize.py` from `outputs/`. Protocol: `PROTOCOL.md` (committed before code and results).",
         "Primary condition: E1 (others' weeks + own past weeks → predict next week), F-mean (daytime weekly mean),",
         "baseline-normalized features, T-raw (nHDRS). 144 predictions (6 patients × C01–C24).", "",
         "## Primary (E1)", "",
         "| Model | R² | r | MAE | mean per-patient r | ΔR² vs time-only (p, circular-shift null) | r (p) | ΔR² vs persistence |",
         "|---|---|---|---|---|---|---|---|"]
for m in P.index:
    row = P.loc[m]
    if m in T.index:
        t = T.loc[m]
        extra = f"{f(t.dR2_vs_time)} (p = {f(t.p_dR2)}) | {f(row.r)} (p = {f(t.p_r)}) | {f(t.dR2_vs_persistence)}"
    else:
        extra = "— | — | —"
    lines.append(f"| {m} | {f(row.R2)} | {f(row.r)} | {f(row.MAE)} | {f(row.mean_pt_r)} | {extra} |")
lines += ["", f"Null: {int(T.n_null.min())} circular-shift draws, every model refit per draw. p = (#null ≥ observed + 1) / (n + 1).", ""]

h1, h2 = T.loc["M3_ENR+time"], T.loc["M6_SVR+time"]
lines += ["## Hypotheses", "",
          f"- **H1** (M3 ENR+time beats time-only): ΔR² = {f(h1.dR2_vs_time)}, p = {f(h1.p_dR2)} → "
          + ("**supported**" if h1.dR2_vs_time > 0 and h1.p_dR2 < 0.05 else "**not supported**"),
          f"- **H2** (M6 SVR+time beats time-only): ΔR² = {f(h2.dR2_vs_time)}, p = {f(h2.p_dR2)} → "
          + ("**supported**" if h2.dR2_vs_time > 0 and h2.p_dR2 < 0.05 else "**not supported**")]
e30 = E3[E3.N == 0].pivot_table(index="model", columns="norm", values="R2")
lines += [f"- **H3** (baseline normalization helps leave-one-patient-out, E3 N = 0; descriptive): "
          f"M2 ENR R² raw {f(e30.loc['M2_ENR','raw'])} → baseline {f(e30.loc['M2_ENR','baseline'])}; "
          f"M5 SVR R² raw {f(e30.loc['M5_SVR','raw'])} → baseline {f(e30.loc['M5_SVR','baseline'])}", ""]

lines += ["## E3 calibration curve (secondary): pooled R² by calibration weeks N", ""]
for norm in ["baseline", "raw"]:
    c = E3[E3.norm == norm].pivot_table(index="model", columns="N", values="R2")
    lines += [f"**{norm} features**", "", "| Model | " + " | ".join(f"N={n}" for n in c.columns) + " |",
              "|---|" + "---|" * len(c.columns)]
    lines += [f"| {m} | " + " | ".join(f(v) for v in c.loc[m]) + " |" for m in c.index]
    lines += [""]

lines += ["## Exploratory: E1 across feature sets, normalization, targets (pooled R² / r)", ""]
for tgt in ["T-raw", "T-smooth", "T-DSC"]:
    a = A1[A1.target == tgt].copy()
    a["cell"] = a.apply(lambda r: f"{f(r.R2, 2)} / {f(r.r, 2)}", axis=1)
    piv = a.pivot_table(index=["fset", "norm"], columns="model", values="cell", aggfunc="first")
    lines += [f"**{tgt}**", "", "| features | norm | " + " | ".join(piv.columns) + " |",
              "|---|---|" + "---|" * len(piv.columns)]
    lines += [f"| {i[0]} | {i[1]} | " + " | ".join(piv.loc[i]) + " |" for i in piv.index]
    lines += [""]

lines += ["## Exploratory: E2 (own past weeks only; linear models)", ""]
a = A2[A2.target == "T-raw"].copy()
a["cell"] = a.apply(lambda r: f"{f(r.R2, 2)} / {f(r.r, 2)}", axis=1)
piv = a.pivot_table(index=["fset", "norm"], columns="model", values="cell", aggfunc="first")
lines += ["T-raw, pooled R² / r", "", "| features | norm | " + " | ".join(piv.columns) + " |",
          "|---|---|" + "---|" * len(piv.columns)]
lines += [f"| {i[0]} | {i[1]} | " + " | ".join(piv.loc[i]) + " |" for i in piv.index]
lines += ["", "<!-- ai-end -->", ""]

# ---- post-hoc (not pre-registered): baseline centering
if (O / "posthoc_center_E1.csv").exists():
    pc1 = pd.read_csv(O / "posthoc_center_E1.csv").set_index("model")
    pc3 = pd.read_csv(O / "posthoc_center_E3_N0.csv").set_index("model")
    lines += ["## Post-hoc (not pre-registered): baseline centering", "", "<!-- ai-start -->",
              "Pre-registered baseline z-scoring divides by σ from only 4 stimulation-off weeks. Once stimulation starts,",
              "features reach |z| ≈ 6 (median) to 95 (max), versus ≤ 7.5 raw: the stimulation-on state moves band power far",
              "outside the off-state range (consistent with the mismatch-compression / stimulation confound, remediation plan CC-1).",
              "`posthoc_center.py` subtracts the B-week mean without scaling (F-mean, T-raw):", "",
              "| Model | E1 R² | E1 r | E3 N=0 R² | E3 N=0 r |", "|---|---|---|---|---|"]
    for m in pc1.index:
        e3v = pc3.loc[m] if m in pc3.index else None
        lines.append(f"| {m} | {f(pc1.loc[m,'R2'])} | {f(pc1.loc[m,'r'])} | "
                     f"{f(e3v.R2) if e3v is not None else '—'} | {f(e3v.r) if e3v is not None else '—'} |")
    lines += ["", "It does not change the conclusions.", "<!-- ai-end -->", ""]

# ---- amendment 1: FOOOF
if (O / "fooof_E1_primary_null.csv").exists():
    F1 = pd.read_csv(O / "fooof_E1_scores.csv")
    FN = pd.read_csv(O / "fooof_E1_primary_null.csv")
    F3 = pd.read_csv(O / "fooof_E3_scores.csv")
    FP = F1[(F1.norm == "raw") & (F1.target == "T-raw")].set_index("model")
    fnw = FN.pivot_table(index="draw", columns="model", values="R2")
    ft = []
    for m in ["M2_ENR", "M3_ENR+time", "M4_mixed", "M5_SVR", "M6_SVR+time"]:
        obs = FP.loc[m, "R2"] - FP.loc["M1_time", "R2"]
        null = (fnw[m] - fnw["M1_time"]).dropna()
        nr = FN[FN.model == m].r.dropna()
        ft.append({"model": m, "dR2": obs, "p": (np.sum(null >= obs) + 1) / (len(null) + 1),
                   "p_r": (np.sum(nr >= FP.loc[m, "r"]) + 1) / (len(nr) + 1), "n": len(null)})
    FT = pd.DataFrame(ft).set_index("model")
    FT.to_csv(O / "fooof_E1_primary_tests.csv")
    lines += ["## Amendment 1: FOOOF features (F-fooof)", "", "<!-- ai-start -->",
              "FOOOF primary condition: E1 × T-raw × F-fooof × raw. Same 100 circular-shift draws as the F-mean null.", "",
              "| Model | R² | r | MAE | mean per-patient r | ΔR² vs time-only (p) | r (p) |", "|---|---|---|---|---|---|---|"]
    for m in FP.index:
        row = FP.loc[m]
        extra = f"{f(FT.loc[m,'dR2'])} (p = {f(FT.loc[m,'p'])}) | {f(row.r)} (p = {f(FT.loc[m,'p_r'])})" if m in FT.index else "— | —"
        lines.append(f"| {m} | {f(row.R2)} | {f(row.r)} | {f(row.MAE)} | {f(row.mean_pt_r)} | {extra} |")
    h4, h5 = FT.loc["M3_ENR+time"], FT.loc["M6_SVR+time"]
    ok = lambda h: "**supported**" if h.dR2 > 0 and h.p < 0.05 else "**not supported**"
    mean_e1 = A1[(A1.fset == "F-mean") & (A1.norm == "raw") & (A1.target == "T-raw")].set_index("model")
    e30f = F3[(F3.N == 0) & (F3.norm == "raw")].set_index("model")
    e30m = E3[(E3.N == 0) & (E3.norm == "raw")].set_index("model")
    lines += ["", f"- **H4** (M3 ENR+time, F-fooof, beats time-only): ΔR² = {f(h4.dR2)}, p = {f(h4.p)} → {ok(h4)}",
              f"- **H5** (M6 SVR+time, F-fooof, beats time-only): ΔR² = {f(h5.dR2)}, p = {f(h5.p)} → {ok(h5)}",
              "- **H6** (descriptive, raw features, T-raw): F-mean → F-fooof, pooled R² / r"]
    for m in ["M2_ENR", "M5_SVR"]:
        lines.append(f"  - {m}: E1 {f(mean_e1.loc[m,'R2'])} / {f(mean_e1.loc[m,'r'])} → {f(FP.loc[m,'R2'])} / {f(FP.loc[m,'r'])}; "
                     f"E3 N=0 {f(e30m.loc[m,'R2'])} / {f(e30m.loc[m,'r'])} → {f(e30f.loc[m,'R2'])} / {f(e30f.loc[m,'r'])}")
    a = F1.copy()
    a["cell"] = a.apply(lambda r: f"{f(r.R2, 2)} / {f(r.r, 2)}", axis=1)
    piv = a.pivot_table(index=["norm", "target"], columns="model", values="cell", aggfunc="first")
    lines += ["", "All F-fooof E1 conditions (pooled R² / r):", "", "| norm | target | " + " | ".join(piv.columns) + " |",
              "|---|---|" + "---|" * len(piv.columns)]
    lines += [f"| {i[0]} | {i[1]} | " + " | ".join(piv.loc[i]) + " |" for i in piv.index]
    c = F3[F3.norm == "raw"].pivot_table(index="model", columns="N", values="R2")
    lines += ["", "F-fooof raw, E3 calibration curve (pooled R²):", "", "| Model | " + " | ".join(f"N={n}" for n in c.columns) + " |",
              "|---|" + "---|" * len(c.columns)]
    lines += [f"| {m} | " + " | ".join(f(v) for v in c.loc[m]) + " |" for m in c.index]
    lines += ["", "<!-- ai-end -->", ""]

# ---- exploratory null for the best FOOOF condition
if (O / "fooof_baseline_E1_tests_EXPLORATORY.csv").exists():
    X = pd.read_csv(O / "fooof_baseline_E1_tests_EXPLORATORY.csv").set_index("model")
    lines += ["## Exploratory: FOOOF × baseline normalization, with its own null", "", "<!-- ai-start -->",
              "Not a pre-registered test: this condition was picked after seeing the F-fooof grid. Same 100 circular-shift",
              "draws. `p (R²)` compares the model's pooled R² with its own null; `p (ΔR²)` compares the gain over time-only.", "",
              "| Model | R² | r | ΔR² vs time-only (p) | p (R²) | ΔR² vs persistence |", "|---|---|---|---|---|---|"]
    for m in X.index:
        x = X.loc[m]
        lines.append(f"| {m} | {f(x.R2)} | {f(x.r)} | {f(x.dR2_vs_time)} (p = {f(x.p_dR2)}) | {f(x.p_R2)} | {f(x.dR2_vs_persistence)} |")
    lines += ["", "Needs confirmation on held-out data (for example the original May 2020 frame, or new patients) before it can be",
              "claimed: it is the best of several FOOOF conditions examined.", "<!-- ai-end -->", ""]

# ---- amendment 2: confirmation
if (O / "confirm_C1_tests.csv").exists():
    C1 = pd.read_csv(O / "confirm_C1_tests.csv").set_index("model")
    C1s = pd.read_csv(O / "confirm_C1_scores.csv").set_index("model")
    yn = lambda v: "yes" if bool(v) else "no"
    lines += ["## Amendment 2, C1: day-vs-night comparison (descriptive; retracted as a confirmation in amendment 4)", "", "<!-- ai-start -->",
              "Daytime and nighttime recordings come from different physiological states, so this is not a valid confirmation test.",
              "The numbers are kept as a descriptive comparison only.",
              "Frozen pipeline (amendment 1) on nighttime recordings only (F-fooof-night × baseline × T-raw, E1, same 100 null draws).",
              f"Persistence R² in this run: {f(C1s.loc['M0_persistence','R2'])}. Criteria, each required: (a) R² > persistence, (b) null p(R²) < 0.05, (c) r > 0.", "",
              "| Model | R² | r | p (R²) | (a) | (b) | (c) | Original C1 call (retracted) |", "|---|---|---|---|---|---|---|---|"]
    for m in C1.index:
        x = C1.loc[m]
        conf = ("**yes**" if x.confirmed == True else "**no**") if m in ("M3_ENR+time", "M4_mixed") else "not a confirmation target"
        lines.append(f"| {m} | {f(x.R2)} | {f(x.r)} | {f(x.p_R2)} | {yn(x.a_beats_persistence)} | {yn(x.b_null_p_lt_05)} | {yn(x.c_r_positive)} | {conf} |")
    lines += ["", "C2 (May 2020 frame) was withdrawn in amendment 3. The selection-corrected test is C3 (amendment 4).",
              "<!-- ai-end -->", ""]

if (O / "confirm_C3_summary.csv").exists():
    c3 = pd.read_csv(O / "confirm_C3_summary.csv").iloc[0]
    cells = pd.read_csv(O / "confirm_C3_cells.csv")
    lines += ["## Amendment 4, C3: selection-corrected test of the FOOOF lead (daytime)", "", "<!-- ai-start -->",
              "Null = the best gain over persistence across all 20 explored FOOOF cells, per circular-shift draw "
              f"({int(c3.n_draws)} draws, same shift offsets in every cell).", "",
              f"- Observed best gain: **{f(c3.observed_max_gain)}** ({c3.cell})",
              f"- Null best gain: mean {f(c3.null_max_mean)}, 95th percentile {f(c3.null_max_95pct)}",
              f"- Selection-corrected p = **{f(c3.p_selection_corrected)}** → " + ("**survives**" if c3.survives else "**does not survive**"), "",
              "| norm | target | model | model R² | model r | persistence R² | persistence r | gain | selection-corrected p |",
              "|---|---|---|---|---|---|---|---|---|"]
    FS = pd.read_csv(O / "fooof_E1_scores.csv").set_index(["norm", "target", "model"])
    for r in cells.itertuples():
        m, p0 = FS.loc[(r.norm, r.target, r.model)], FS.loc[(r.norm, r.target, "M0_persistence")]
        lines.append(f"| {r.norm} | {r.target} | {r.model} | {f(m.R2)} | {f(m.r)} | {f(p0.R2)} | {f(p0.r)} | "
                     f"{f(r.gain_vs_persistence)} | {f(r.p_selection_corrected)} |")
    lines += ["", "<!-- ai-end -->", ""]

(HERE / "RESULTS.md").write_text("\n".join(lines))
print("\n".join(lines[:40]))
