"""Build RESULTS.md from outputs/*.csv (no model fitting)."""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
O = HERE / "outputs"
P = pd.read_csv(O / "E1_primary_scores.csv").set_index("model")
NULL = pd.read_csv(O / "E1_primary_null.csv")
E3 = pd.read_csv(O / "E3_scores.csv")
A1 = pd.read_csv(O / "E1_all_scores.csv")
A2 = pd.read_csv(O / "E2_all_scores.csv")


def f(x, d=3):
    return "—" if pd.isna(x) else f"{x:.{d}f}"


# ---- null: delta R2 vs M1 per draw
nw = NULL.pivot_table(index="draw", columns="model", values="R2")
tests = []
for m in ["M2_ENR", "M3_ENR+time", "M4_mixed", "M5_SVR", "M6_SVR+time"]:
    obs = P.loc[m, "R2"] - P.loc["M1_time", "R2"]
    null = (nw[m] - nw["M1_time"]).dropna()
    obs_r = P.loc[m, "r"]
    null_r = NULL[NULL.model == m].r.dropna()
    tests.append({"model": m, "dR2_vs_time": obs, "p_dR2": (np.sum(null >= obs) + 1) / (len(null) + 1),
                  "r": obs_r, "p_r": (np.sum(null_r >= obs_r) + 1) / (len(null_r) + 1),
                  "dR2_vs_persistence": P.loc[m, "R2"] - P.loc["M0_persistence", "R2"], "n_null": len(null)})
T = pd.DataFrame(tests).set_index("model")
T.to_csv(O / "E1_primary_tests.csv")

lines = ["# DR-SCC forward chaining: results", "", "<!-- ai-start -->",
         "Generated by `summarize.py` from `outputs/`. Protocol: `PROTOCOL.md` (committed before code and results).",
         "Primary condition: E1 (others' weeks + own past weeks → predict next week), F-mean (daytime weekly mean),",
         "baseline-normalized features, T-raw (nHDRS). 144 predictions (6 patients × C01–C24).", "",
         "## Primary (E1)", "",
         "| Model | R² | r | MAE | mean per-patient r | ΔR² vs time-only (p, circular-shift null) | r (p) | ΔR² vs persistence |",
         "|---|---|---|---|---|---|---|---|"]
for m in P.index:
    row = P.loc[m]
    if m in T.index:
        t = T.loc[m]
        extra = f"{f(t.dR2_vs_time)} (p = {f(t.p_dR2)}) | {f(row.r)} (p = {f(t.p_r)}) | {f(t.dR2_vs_persistence)}"
    else:
        extra = "— | — | —"
    lines.append(f"| {m} | {f(row.R2)} | {f(row.r)} | {f(row.MAE)} | {f(row.mean_pt_r)} | {extra} |")
lines += ["", f"Null: {int(T.n_null.min())} circular-shift draws, every model refit per draw. p = (#null ≥ observed + 1) / (n + 1).", ""]

h1, h2 = T.loc["M3_ENR+time"], T.loc["M6_SVR+time"]
lines += ["## Hypotheses", "",
          f"- **H1** (M3 ENR+time beats time-only): ΔR² = {f(h1.dR2_vs_time)}, p = {f(h1.p_dR2)} → "
          + ("**supported**" if h1.dR2_vs_time > 0 and h1.p_dR2 < 0.05 else "**not supported**"),
          f"- **H2** (M6 SVR+time beats time-only): ΔR² = {f(h2.dR2_vs_time)}, p = {f(h2.p_dR2)} → "
          + ("**supported**" if h2.dR2_vs_time > 0 and h2.p_dR2 < 0.05 else "**not supported**")]
e30 = E3[E3.N == 0].pivot_table(index="model", columns="norm", values="R2")
lines += [f"- **H3** (baseline normalization helps leave-one-patient-out, E3 N = 0; descriptive): "
          f"M2 ENR R² raw {f(e30.loc['M2_ENR','raw'])} → baseline {f(e30.loc['M2_ENR','baseline'])}; "
          f"M5 SVR R² raw {f(e30.loc['M5_SVR','raw'])} → baseline {f(e30.loc['M5_SVR','baseline'])}", ""]

lines += ["## E3 calibration curve (secondary): pooled R² by calibration weeks N", ""]
for norm in ["baseline", "raw"]:
    c = E3[E3.norm == norm].pivot_table(index="model", columns="N", values="R2")
    lines += [f"**{norm} features**", "", "| Model | " + " | ".join(f"N={n}" for n in c.columns) + " |",
              "|---|" + "---|" * len(c.columns)]
    lines += [f"| {m} | " + " | ".join(f(v) for v in c.loc[m]) + " |" for m in c.index]
    lines += [""]

lines += ["## Exploratory: E1 across feature sets, normalization, targets (pooled R² / r)", ""]
for tgt in ["T-raw", "T-smooth", "T-DSC"]:
    a = A1[A1.target == tgt].copy()
    a["cell"] = a.apply(lambda r: f"{f(r.R2, 2)} / {f(r.r, 2)}", axis=1)
    piv = a.pivot_table(index=["fset", "norm"], columns="model", values="cell", aggfunc="first")
    lines += [f"**{tgt}**", "", "| features | norm | " + " | ".join(piv.columns) + " |",
              "|---|---|" + "---|" * len(piv.columns)]
    lines += [f"| {i[0]} | {i[1]} | " + " | ".join(piv.loc[i]) + " |" for i in piv.index]
    lines += [""]

lines += ["## Exploratory: E2 (own past weeks only; linear models)", ""]
a = A2[A2.target == "T-raw"].copy()
a["cell"] = a.apply(lambda r: f"{f(r.R2, 2)} / {f(r.r, 2)}", axis=1)
piv = a.pivot_table(index=["fset", "norm"], columns="model", values="cell", aggfunc="first")
lines += ["T-raw, pooled R² / r", "", "| features | norm | " + " | ".join(piv.columns) + " |",
          "|---|---|" + "---|" * len(piv.columns)]
lines += [f"| {i[0]} | {i[1]} | " + " | ".join(piv.loc[i]) + " |" for i in piv.index]
lines += ["", "<!-- ai-end -->", ""]
(HERE / "RESULTS.md").write_text("\n".join(lines))
print("\n".join(lines[:40]))
