"""Build RESULTS.md for the phase-offset analysis from outputs/ (no fitting). Raw values; coherency beside every phase."""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
O = HERE / "outputs"
f = lambda x, d=2: "—" if pd.isna(x) else f"{x:.{d}f}"
P = pd.read_csv(O / "ph1_description.csv", dtype={"pt": str})
C2 = pd.read_csv(O / "ph2_contrasts.csv", dtype={"pt": str})
CN = pd.read_csv(O / "ph2_consistency.csv")
H = pd.read_csv(O / "ph3_phase_vs_nhdrs.csv", dtype={"pt": str})
CL = pd.read_csv(O / "ph3_classification.csv", dtype={"pt": str})
CP = pd.read_csv(O / "ph3_classification_permutation.csv")
ST = pd.read_csv(O / "home_stim_state_by_phase.csv")
PTS = sorted(P.pt.unique())
ORDER = ["delta", "theta", "alpha", "beta", "bstar", "gamma", "gamma1"]
CONDS = ["day/off", "night/off", "day/on", "night/on", "session/off", "session/on"]

L = ["# Left–right SCC phase offset: results", "", "<!-- ai-start -->",
     "Generated by `phase_summarize.py`. Protocol: `PROTOCOL.md` (committed before code and results).",
     "Phase φ > 0 means the right channel leads the left. Channels are bipolar, so values near ±180° can reflect electrode polarity.",
     "Every phase is shown with its coherency magnitude; the surrogate magnitude is what unrelated signals with the same spectra give.", "",
     "## Stimulation state of the at-home recordings (130 Hz line)", "",
     "Recordings by study phase (B = before stimulation, C = during therapy), time of day and detected stimulation state:", "",
     "```", ST.to_string(index=False), "```", "",
     "A sizeable share of C-week recordings show no 130 Hz line. The line can be cancelled by the differential recording when the two "
     "contacts are well matched, so \"off\" here means \"no detectable stimulation artefact\", not necessarily that the stimulator was off.", "",
     "## PH1: description (median across patients)", "",
     "| Correction | Condition | Band | coherency magnitude | surrogate magnitude | imaginary coherency | fraction of weeks reliable | phase by patient (°) |",
     "|---|---|---|---|---|---|---|---|"]
for corr in ("uncorrected", "corrected"):
    for cond in CONDS:
        for b in ORDER:
            g = P[(P["corr"] == corr) & (P.cond == cond) & (P.band == b)]
            if g.empty:
                continue
            ph = ", ".join(f"{r.pt}: {r.phase_deg:.0f}" for r in g.itertuples() if not pd.isna(r.phase_deg))
            L.append(f"| {corr} | {cond} | {b} | {f(g.coherency_mag_median.median())} | {f(g.surrogate_mag_median.median())} | "
                     f"{f(g.imag_coh_median.median(), 3)} | {f(g.frac_reliable.median())} | {ph} |")
L += ["", "Per-patient values, including resultant length and week counts, are in `outputs/ph1_description.csv`.", "",
      "## PH2: contrasts", "",
      "Consistent = q < 0.05 with the same sign in ≥ 3 of 4 patients (sessions) or ≥ 4 of 6 (at-home).", "",
      "| Contrast | Detail | Bands / correction | Band | patients tested | significant (+ / −) | median Δ (°) | consistent |",
      "|---|---|---|---|---|---|---|---|"]
for r in CN.itertuples():
    L.append(f"| {r.contrast} | {r.detail if isinstance(r.detail, str) else ''} | {r.corr} | {r.band} | {r.n_patients} | {r.n_sig_pos} / {r.n_sig_neg} | "
             f"{f(r.median_delta_deg, 1)} | {'**yes**' if r.consistent else 'no'} |")
sig = C2[C2.q < 0.05]
L += ["", f"Individual patient × band tests significant after FDR: {len(sig)} of {len(C2)}. Listed:", "",
      "| Contrast | Detail | Correction | Patient | Band | weeks | Δ (°) | q |", "|---|---|---|---|---|---|---|---|"]
L += [f"| {r.contrast} | {r.detail if isinstance(r.detail, str) else ''} | {r.corr} | {r.pt} | {r.band} | {r.n_weeks} | {f(r.delta_deg, 1)} | {f(r.q, 3)} |"
      for r in sig.sort_values(["contrast", "pt"]).itertuples()]
L += ["", "## PH3: relation to depression", "",
      f"Weekly phase versus nHDRS (within patient, corrected bands): {int((H.q < 0.05).sum())} of {len(H)} patient × band × condition cells "
      f"have q < 0.05; smallest q = {f(H.q.min(), 3)}.", "",
      "| Condition | Patient | Band | weeks | R² | null R² (mean) | p | q | coherency magnitude |", "|---|---|---|---|---|---|---|---|---|"]
L += [f"| {r.cond} | {r.pt} | {r.band} | {r.n_weeks} | {f(r.R2)} | {f(r.null_R2_mean)} | {f(r.p, 3)} | {f(r.q, 3)} | {f(r.coherency_mag_median)} |"
      for r in H.sort_values("p").head(8).itertuples()]
L += ["", "Sick vs stable in the stimulation-off sessions (logistic regression; leave one patient out among 906–908; 905 held out):", "",
      "| Features | Analysis | Patient | AUROC (segments) | AUROC (sessions) |", "|---|---|---|---|---|"]
L += [f"| {r.features} | {r.analysis} | {r.pt} | {f(r.auc_segment, 3)} | {f(r.auc_session, 3)} |" for r in CL.itertuples()]
L += ["", "| Features | mean segment AUROC (906–908) | null mean | null 95th pct | permutation p |", "|---|---|---|---|---|"]
L += [f"| {r.features} | {f(r.obs_auc_segment_mean, 3)} | {f(r.null_mean, 3)} | {f(r.null_95, 3)} | {f(r.p, 3)} |" for r in CP.itertuples()]
ph = CP[CP.features.str.startswith("phase")].iloc[0]
any_c = lambda prefix: bool(CN[CN.contrast.str.startswith(prefix)].consistent.any())
L += ["", "## Hypotheses", "",
      f"- **H-P1** (stimulation changes the phase offset consistently): " + ("**supported**" if any_c("ii ") else "**not supported**"),
      f"- **H-P2** (day and night differ consistently): " + ("**supported**" if any_c("i ") else "**not supported**"),
      f"- **H-P3** (mismatch-compression correction changes the phase estimate consistently): " + ("**supported**" if any_c("iv ") else "**not supported**"),
      f"- **H-P4** (phase classifies sick vs stable): mean AUROC {f(ph.obs_auc_segment_mean, 3)}, p = {f(ph.p, 3)} → "
      + ("**supported**" if ph.obs_auc_segment_mean > 0.5 and ph.p < 0.05 else "**not supported**"),
      "", "<!-- ai-end -->", ""]
(HERE / "RESULTS.md").write_text("\n".join(L))
print("written", len(L))
