"""Build RESULTS.md for the weekly in-clinic session analyses from outputs/ (no fitting). Raw values always shown."""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
O = HERE / "outputs"
f = lambda x, d=3: "—" if pd.isna(x) else f"{x:.{d}f}"
PTS = ["905", "906", "907", "908"]
L = ["# DR-SCC weekly in-clinic sessions: results", "", "<!-- ai-start -->",
     "Generated by `wd_summarize.py`. Protocol: `PROTOCOL.md` and amendment W-A1 (written after the first run; see below).",
     "Patients 905–908; stimulation-off segments of single-file weekly sessions; 10-s segments. All values raw.", ""]

A2 = pd.read_csv(O / "a2_auc.csv", dtype={"pt": str})
TS = pd.read_csv(O / "a2_time_vs_state.csv", dtype={"pt": str})
L += ["## (a) Replication of Alagapan et al. 2023 (amendment W-A1 design)", "",
      "Paper: neural network, leave-one-participant-out over five typical responders, AUROC 0.87 ± 0.09.", "",
      "| Analysis | Model | Patient | Sessions | AUROC (segments) | AUROC (sessions) |", "|---|---|---|---|---|---|"]
L += [f"| {r.analysis} | {r.model} | {r.pt} | {int(r.n_sessions)} | {f(r.auc_segment)} | {f(r.auc_session)} |" for r in A2.itertuples()]
L += ["", "Time versus state: session score = mean predicted P(stable) from a model that never saw the patient; all C-week sessions.", "",
      "| Model | Patient | Sessions | ρ(score, nHDRS) | p | ρ(score, week) | p | ρ(nHDRS, week) | p |", "|---|---|---|---|---|---|---|---|---|"]
L += [f"| {r.model} | {r.pt} | {int(r.n_sessions)} | {f(r.rho_score_nHDRS)} | {f(r.p_score_nHDRS)} | {f(r.rho_score_week)} | "
      f"{f(r.p_score_week)} | {f(r.rho_nHDRS_week)} | {f(r.p_nHDRS_week)} |" for r in TS.itertuples()]

A = pd.read_csv(O / "a_b_contrasts.csv", dtype={"held_out": str})
L += ["", "## (b) Checks", "", "### First run as pre-registered (all four patients, calendar-block labels)", "",
      "The nHDRS gap is the pooled mean of the second block minus the first.", "",
      "| Contrast | Model | nHDRS gap | " + " | ".join(f"{p} seg / ses" for p in PTS) + " | mean seg | mean ses |",
      "|---|---|---|" + "---|" * (len(PTS) + 2)]
for (c, m), g in A.groupby(["contrast", "model"], sort=False):
    g = g.set_index("held_out")
    L.append(f"| {c} | {m} | {f(g.nHDRS_gap.iloc[0])} | " + " | ".join(f"{f(g.loc[p,'auc_segment'],2)} / {f(g.loc[p,'auc_session'],2)}" for p in PTS)
             + f" | {f(g.auc_segment.mean())} | {f(g.auc_session.mean())} |")
SF = pd.read_csv(O / "b1_single_features.csv")
B3 = pd.read_csv(O / "b3_permutation_test.csv").iloc[0]
L += ["", "### B1: single features, sick vs stable (direction learned on training patients; segment AUROC)", "",
      "| Feature | mean | " + " | ".join(PTS) + " |", "|---|---|" + "---|" * len(PTS)]
L += [f"| {r.feature} | {f(r.auc_segment_mean)} | " + " | ".join(f(getattr(r, f'auc_{p}'), 2) for p in PTS) + " |" for r in SF.head(8).itertuples()]
L += ["", f"### B3: permutation test (logistic regression, labels permuted within patient, 200 permutations; all four patients)", "",
      f"Observed mean AUROC: segments {f(B3.obs_auc_segment)} (p = {f(B3.p_segment)}), sessions {f(B3.obs_auc_session)} (p = {f(B3.p_session)}).", ""]

if (O / "b4_forward_chain_scores.csv").exists():
    B4 = pd.read_csv(O / "b4_forward_chain_scores.csv")
    N4 = pd.read_csv(O / "b4_null.csv")
    dmax = N4.groupby("draw").gain.max()
    L += ["### B4: continuous tracking of nHDRS, forward chaining (paper feature set, session medians)", "",
          f"Null: best gain over persistence across the 10 neural cells per circular-shift draw ({len(dmax)} draws): mean {f(dmax.mean())}, "
          f"95th pct {f(dmax.quantile(0.95))}.", "",
          "| Normalization | Model | n | R² | r | MAE | persistence R² | gain | selection-corrected p |", "|---|---|---|---|---|---|---|---|---|"]
    for norm, g in B4.groupby("norm", sort=False):
        p0 = g[g.model == "M0_persistence"].R2.iloc[0]
        for r in g.itertuples():
            neural = r.model not in ("M0_persistence", "M1_time")
            gain = r.R2 - p0
            pv = (np.sum(dmax >= gain) + 1) / (len(dmax) + 1) if neural else np.nan
            L.append(f"| {norm} | {r.model} | {int(r.n)} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} | {f(p0)} | {f(gain) if neural else '—'} | {f(pv)} |")
    L += [""]

if (O / "c1_agreement_summary.csv").exists():
    C1 = pd.read_csv(O / "c1_agreement_summary.csv")
    C1p = pd.read_csv(O / "c1_agreement_by_patient.csv", dtype={"pt": str})
    L += ["## (c) Extension to the at-home recordings", "",
          "### C1: does each at-home (stimulation-on) weekly feature agree with the same week's stimulation-off value?", "",
          "Within-patient Spearman ρ across C weeks. Validated = ρ > 0 with FDR q < 0.05 in ≥ 3 of 4 patients.", "",
          "| Feature | " + " | ".join(f"ρ {p}" for p in PTS) + " | mean ρ | patients validated | validated | mean ρ (at-home vs GCr) | patients GCr-significant |",
          "|---|" + "---|" * (len(PTS) + 5)]
    for r in C1.itertuples():
        pp = C1p[C1p.feature == r.feature].set_index("pt")
        L.append(f"| `{r.feature}` | " + " | ".join(f(pp.loc[p, 'rho_off_vs_home'], 2) for p in PTS) + f" | {f(r.rho_mean, 2)} | {int(r.n_validated_pts)} | "
                 f"{'**yes**' if r.validated else 'no'} | {f(r.rho_GCr_mean, 2)} | {int(r.n_GCr_sig_pts)} |")
    C2 = pd.read_csv(O / "c2_stim_on_minus_off.csv", dtype={"pt": str})
    L += ["", "### C2: stimulation-on minus stimulation-off within the same session", "",
          "Effect in units of the week-to-week SD of the stimulation-off value (mean over C-week sessions).", "",
          "| Feature | " + " | ".join(f"{p}: off / on / effect" for p in PTS) + " |", "|---|" + "---|" * len(PTS)]
    for ft, g in C2.groupby("feature", sort=False):
        g = g.set_index("pt")
        L.append(f"| `{ft}` | " + " | ".join((f"{f(g.loc[p,'off_mean'],2)} / {f(g.loc[p,'on_mean'],2)} / {f(g.loc[p,'effect_in_week_sd'],1)}"
                                               if p in g.index else "—") for p in PTS) + " |")
    for name, fn in (("C3: forward chaining on the same four patients and weeks", "c3_transfer_scores.csv"),
                     ("C4: co-coherence added to the chronic features, all six patients, forward chaining", "c4_coherence_scores.csv")):
        T = pd.read_csv(O / fn)
        L += ["", f"### {name}", "", "| Features | Model | n | R² | r | MAE |", "|---|---|---|---|---|---|"]
        L += [f"| {r.features} | {r.model} | {int(r.n)} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} |" for r in T.itertuples()]
L += ["", "<!-- ai-end -->", ""]
(HERE / "RESULTS.md").write_text("\n".join(L))
print("written", len(L), "lines")
