"""Build RESULTS.md for the weekly in-clinic session analyses from outputs/ (no fitting). Raw values always shown."""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
O = HERE / "outputs"
f = lambda x, d=3: "—" if pd.isna(x) else f"{x:.{d}f}"
PTS = ["905", "906", "907", "908"]
L = ["# DR-SCC weekly in-clinic sessions: results", "", "<!-- ai-start -->",
     "Generated by `wd_summarize.py`. Protocol: `PROTOCOL.md` and amendment W-A1 (written after the first run; see below).",
     "Patients 905–908; stimulation-off segments of single-file weekly sessions; 10-s segments. All values raw.", ""]

A2 = pd.read_csv(O / "a2_auc.csv", dtype={"pt": str})
TS = pd.read_csv(O / "a2_time_vs_state.csv", dtype={"pt": str})
L += ["## (a) Replication of Alagapan et al. 2023 (amendment W-A1 design)", "",
      "Paper: neural network, leave-one-participant-out over five typical responders, AUROC 0.87 ± 0.09.", "",
      "| Analysis | Model | Patient | Sessions | AUROC (segments) | AUROC (sessions) |", "|---|---|---|---|---|---|"]
L += [f"| {r.analysis} | {r.model} | {r.pt} | {int(r.n_sessions)} | {f(r.auc_segment)} | {f(r.auc_session)} |" for r in A2.itertuples()]
L += ["", "Time versus state: session score = mean predicted P(stable) from a model that never saw the patient; all C-week sessions.", "",
      "| Model | Patient | Sessions | ρ(score, nHDRS) | p | ρ(score, week) | p | ρ(nHDRS, week) | p |", "|---|---|---|---|---|---|---|---|---|"]
L += [f"| {r.model} | {r.pt} | {int(r.n_sessions)} | {f(r.rho_score_nHDRS)} | {f(r.p_score_nHDRS)} | {f(r.rho_score_week)} | "
      f"{f(r.p_score_week)} | {f(r.rho_nHDRS_week)} | {f(r.p_nHDRS_week)} |" for r in TS.itertuples()]

A = pd.read_csv(O / "a_b_contrasts.csv", dtype={"held_out": str})
L += ["", "## (b) Checks", "", "### First run as pre-registered (all four patients, calendar-block labels)", "",
      "The nHDRS gap is the pooled mean of the second block minus the first.", "",
      "| Contrast | Model | nHDRS gap | " + " | ".join(f"{p} seg / ses" for p in PTS) + " | mean seg | mean ses |",
      "|---|---|---|" + "---|" * (len(PTS) + 2)]
for (c, m), g in A.groupby(["contrast", "model"], sort=False):
    g = g.set_index("held_out")
    L.append(f"| {c} | {m} | {f(g.nHDRS_gap.iloc[0])} | " + " | ".join(f"{f(g.loc[p,'auc_segment'],2)} / {f(g.loc[p,'auc_session'],2)}" for p in PTS)
             + f" | {f(g.auc_segment.mean())} | {f(g.auc_session.mean())} |")
SF = pd.read_csv(O / "b1_single_features.csv")
B3 = pd.read_csv(O / "b3_permutation_test.csv").iloc[0]
L += ["", "### B1: single features, sick vs stable (direction learned on training patients; segment AUROC)", "",
      "| Feature | mean | " + " | ".join(PTS) + " |", "|---|---|" + "---|" * len(PTS)]
L += [f"| {r.feature} | {f(r.auc_segment_mean)} | " + " | ".join(f(getattr(r, f'auc_{p}'), 2) for p in PTS) + " |" for r in SF.head(8).itertuples()]
L += ["", f"### B3: permutation test (logistic regression, labels permuted within patient, 200 permutations; all four patients)", "",
      f"Observed mean AUROC: segments {f(B3.obs_auc_segment)} (p = {f(B3.p_segment)}), sessions {f(B3.obs_auc_session)} (p = {f(B3.p_session)}).", ""]

if (O / "b4_forward_chain_scores.csv").exists():
    B4 = pd.read_csv(O / "b4_forward_chain_scores.csv")
    N4 = pd.read_csv(O / "b4_null.csv")
    dmax = N4.groupby("draw").gain.max()
    L += ["### B4: continuous tracking of nHDRS, forward chaining (paper feature set, session medians)", "",
          f"Null: best gain over persistence across the 10 neural cells per circular-shift draw ({len(dmax)} draws): mean {f(dmax.mean())}, "
          f"95th pct {f(dmax.quantile(0.95))}.", "",
          "| Normalization | Model | n | R² | r | MAE | persistence R² | gain | selection-corrected p |", "|---|---|---|---|---|---|---|---|---|"]
    for norm, g in B4.groupby("norm", sort=False):
        p0 = g[g.model == "M0_persistence"].R2.iloc[0]
        for r in g.itertuples():
            neural = r.model not in ("M0_persistence", "M1_time")
            gain = r.R2 - p0
            pv = (np.sum(dmax >= gain) + 1) / (len(dmax) + 1) if neural else np.nan
            L.append(f"| {norm} | {r.model} | {int(r.n)} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} | {f(p0)} | {f(gain) if neural else '—'} | {f(pv)} |")
    L += [""]

if (O / "c1_agreement_summary.csv").exists():
    C1 = pd.read_csv(O / "c1_agreement_summary.csv")
    C1p = pd.read_csv(O / "c1_agreement_by_patient.csv", dtype={"pt": str})
    L += ["## (c) Extension to the at-home recordings", "",
          "### C1: does each at-home (stimulation-on) weekly feature agree with the same week's stimulation-off value?", "",
          "Within-patient Spearman ρ across C weeks. Validated = ρ > 0 with FDR q < 0.05 in ≥ 3 of 4 patients.", "",
          "| Feature | " + " | ".join(f"ρ {p}" for p in PTS) + " | mean ρ | patients validated | validated | mean ρ (at-home vs GCr) | patients GCr-significant |",
          "|---|" + "---|" * (len(PTS) + 5)]
    for r in C1.itertuples():
        pp = C1p[C1p.feature == r.feature].set_index("pt")
        L.append(f"| `{r.feature}` | " + " | ".join(f(pp.loc[p, 'rho_off_vs_home'], 2) for p in PTS) + f" | {f(r.rho_mean, 2)} | {int(r.n_validated_pts)} | "
                 f"{'**yes**' if r.validated else 'no'} | {f(r.rho_GCr_mean, 2)} | {int(r.n_GCr_sig_pts)} |")
    C2 = pd.read_csv(O / "c2_stim_on_minus_off.csv", dtype={"pt": str})
    L += ["", "### C2: stimulation-on minus stimulation-off within the same session", "",
          "Effect in units of the week-to-week SD of the stimulation-off value (mean over C-week sessions).", "",
          "| Feature | " + " | ".join(f"{p}: off / on / effect" for p in PTS) + " |", "|---|" + "---|" * len(PTS)]
    for ft, g in C2.groupby("feature", sort=False):
        g = g.set_index("pt")
        L.append(f"| `{ft}` | " + " | ".join((f"{f(g.loc[p,'off_mean'],2)} / {f(g.loc[p,'on_mean'],2)} / {f(g.loc[p,'effect_in_week_sd'],1)}"
                                               if p in g.index else "—") for p in PTS) + " |")
    for name, fn in (("C3: forward chaining on the same four patients and weeks", "c3_transfer_scores.csv"),
                     ("C4: co-coherence added to the chronic features, all six patients, forward chaining", "c4_coherence_scores.csv")):
        T = pd.read_csv(O / fn)
        L += ["", f"### {name}", "", "| Features | Model | n | R² | r | MAE |", "|---|---|---|---|---|---|"]
        L += [f"| {r.features} | {r.model} | {int(r.n)} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} |" for r in T.itertuples()]
L += ["", "<!-- ai-end -->", ""]

# ---------------------------------------------------------------- amendment W-A2: stimulation-effect correction
if (O / "s_v2_scores.csv").exists():
    D1 = pd.read_csv(O / "s_d1_agreement.csv", dtype={"pt": str})
    V1 = pd.read_csv(O / "s_v1_summary.csv")
    S = pd.read_csv(O / "s_v2_scores.csv")
    L += ["## Amendment W-A2: removing the stimulation effect from the at-home recordings", "", "<!-- ai-start -->",
          "### D1: what the at-home weekly values agree with (mean within-patient Spearman ρ across C weeks)", "",
          "| Feature set | at-home vs session-on | at-home vs session-off | session-on vs session-off |", "|---|---|---|---|"]
    for s_, gdf in D1.groupby("set", sort=False):
        L.append(f"| {s_} | {f(gdf.rho_on_vs_home.mean())} | {f(gdf.rho_off_vs_home.mean())} | {f(gdf.rho_on_vs_off.mean())} |")
    L += ["", "### V1: agreement of corrected at-home values with the stimulation-off session", "",
          "| Feature set | Correction | mean ρ | features validated |", "|---|---|---|---|"]
    for (s_, k), gdf in V1.groupby(["set", "correction"], sort=False):
        L.append(f"| {s_} | {k} | {f(gdf.rho_mean.mean())} | {int(gdf.validated.sum())} of {len(gdf)} |")
    L += ["", "### V2: forward chaining on the session weeks (66 predictions; 905–908)", ""]
    pers = S[S.model == "M0_persistence"].iloc[0]
    tim = S[S.model == "M1_time"].iloc[0]
    L += [f"Persistence: R² {f(pers.R2)}, r {f(pers.r)}, MAE {f(pers.MAE)}. Time-only: R² {f(tim.R2)}, r {f(tim.r)}, MAE {f(tim.MAE)}.", ""]
    neural = S[~S.model.isin(["M0_persistence", "M1_time"])].copy()
    neural["gain"] = neural.R2 - pers.R2
    if (O / "s_v2_null.csv").exists():
        N = pd.read_csv(O / "s_v2_null.csv")
        dmax = N.groupby("draw").gain.max()
        neural["p_corr"] = [(np.sum(dmax >= gval) + 1) / (len(dmax) + 1) if k in ("K1", "K3", "K4") else np.nan
                            for gval, k in zip(neural.gain, neural.correction)]
        L += [f"Null: best gain over persistence across the 60 corrected cells per circular-shift draw ({len(dmax)} draws): "
              f"mean {f(dmax.mean())}, 95th pct {f(dmax.quantile(0.95))}.", ""]
    else:
        neural["p_corr"] = np.nan
    L += ["| Correction | Feature set | Normalization | Model | R² | r | MAE | persistence R² | gain | selection-corrected p | "
          + " | ".join(f"R² {p}" for p in PTS) + " |", "|---|---|---|---|---|---|---|---|---|---|" + "---|" * len(PTS)]
    for r in neural.sort_values("R2", ascending=False).head(20).itertuples():
        L.append(f"| {r.correction} | {r.set} | {r.norm} | {r.model} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} | {f(pers.R2)} | {f(r.gain)} | {f(r.p_corr)} | "
                 + " | ".join(f(getattr(r, f'R2_{p}'), 2) for p in PTS) + " |")
    L += ["", "K0 = uncorrected at-home; OFF = stimulation-off session features (references, not in the corrected family, so no corrected p).",
          "Top 20 of all cells by R²; the full table is `outputs/s_v2_scores.csv`.", "", "Best cell per correction (any feature set, normalization, model):", "",
          "| Correction | Feature set | Normalization | Model | R² | r | MAE |", "|---|---|---|---|---|---|---|"]
    for k, gdf in neural.groupby("correction", sort=False):
        b = gdf.sort_values("R2", ascending=False).iloc[0]
        L.append(f"| {k} | {b.set} | {b.norm} | {b.model} | {f(b.R2)} | {f(b.r)} | {f(b.MAE)} |")
    bc = neural[neural.correction.isin(["K1", "K3", "K4"])].sort_values("R2", ascending=False).iloc[0]
    k0 = neural[neural.correction == "K0"].sort_values("R2", ascending=False).iloc[0]
    of = neural[neural.correction == "OFF"].sort_values("R2", ascending=False).iloc[0]
    nval = {k: int(V1[V1.correction == k].validated.sum()) for k in ("K0", "K3", "K4")}
    L += ["", "### Hypotheses", "",
          f"- **S1** (descriptive): at-home values agree more with the session's stimulation-on values than with its stimulation-off values "
          f"(table D1), but on and off barely track each other across weeks.",
          f"- **S2** (K3 or K4 validates a feature where K0 has none): validated features K0 {nval['K0']}, K3 {nval['K3']}, K4 {nval['K4']} → "
          + ("**supported**" if (nval["K3"] > 0 or nval["K4"] > 0) and nval["K0"] == 0 else "**not supported**"),
          f"- **S3** (a corrected cell beats persistence, selection-corrected p < 0.05): best {bc.correction} × {bc.set} × {bc.norm} × {bc.model}: "
          f"R² {f(bc.R2)} vs persistence {f(pers.R2)} (gain {f(bc.gain)}), r {f(bc.r)} vs {f(pers.r)}, selection-corrected p = {bc.p_corr:.4f} → "
          + ("**supported (marginally)**" if bc.gain > 0 and bc.p_corr < 0.05 else "**not supported**")
          + f". Per patient R²: " + ", ".join(f"{p_} {f(getattr(bc, 'R2_' + p_), 2)}" for p_ in PTS) + ".",
          f"- **S4** (descriptive, same weeks): best corrected R² {f(bc.R2)}, r {f(bc.r)}, MAE {f(bc.MAE)}; best uncorrected (K0: {k0.set}, {k0.norm}, {k0.model}) "
          f"R² {f(k0.R2)}, r {f(k0.r)}, MAE {f(k0.MAE)}; best stimulation-off session ({of.set}, {of.model}) R² {f(of.R2)}, r {f(of.r)}, MAE {f(of.MAE)}; "
          f"persistence R² {f(pers.R2)}, r {f(pers.r)}, MAE {f(pers.MAE)}."]
    L += ["", "<!-- ai-end -->", ""]

(HERE / "RESULTS.md").write_text("\n".join(L))
print("written", len(L), "lines")
