"""Build RESULTS.md for cross-patient phase 1 from outputs/ (no fitting). Raw values always shown."""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
O = HERE / "outputs"
S = pd.read_csv(O / "lopo_scores_with_p.csv")
R = pd.read_csv(O / "lopo_reference_scores.csv")
N = pd.read_csv(O / "lopo_null.csv")
C = pd.read_csv(O / "calibration_best_cell.csv")
D = pd.read_csv(O / "mc_screen_dropped.csv")
PTS = ["901", "903", "905", "906", "907", "908"]
f = lambda x, d=3: "—" if pd.isna(x) else f"{x:.{d}f}"
dmax = N.groupby("draw").R2.max()
ref = R[R.mc == False].set_index("model")

L = ["# DR-SCC cross-patient decoding, phase 1: results", "", "<!-- ai-start -->",
     "Generated by `summarize_xp.py`. Protocol: `PROTOCOL.md` (committed before code and results).",
     "Calibration-free leave-one-patient-out: no label from the held-out patient is used anywhere. Pooled over 144",
     "held-out patient-weeks (C01–C24 × 6 patients). All values are raw.", "",
     "## Reference predictors (raw)", "", "| MC screen | Predictor | R² | r | MAE |", "|---|---|---|---|---|"]
L += [f"| {'on' if r.mc else 'off'} | {r.model} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} |" for r in R.itertuples()]
L += ["", f"Selection-corrected null: best pooled R² over all {S.shape[0]} cells per circular-shift draw ({len(dmax)} draws): "
      f"mean {f(dmax.mean())}, 95th percentile {f(dmax.quantile(0.95))}.", "",
      "## All cells, ranked by pooled R²", "",
      "| MC | Family | Alignment | Model | R² | r | MAE | p (selection-corrected) | p (this cell) | " +
      " | ".join(f"R² {p}" for p in PTS) + " |", "|---|---|---|---|---|---|---|---|---|" + "---|" * len(PTS)]
for r in S.sort_values("R2", ascending=False).itertuples():
    L.append(f"| {'on' if r.mc else 'off'} | {r.family} | {r.align} | {r.model} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} | "
             f"{f(r.p_selection_corrected)} | {f(r.p_uncorrected)} | " + " | ".join(f(getattr(r, f'R2_{p}'), 2) for p in PTS) + " |")

best = S.sort_values("R2", ascending=False).iloc[0]
fp = S[(S["mc"] == True) & (S["family"] == "F-riem") & (S["align"] == "riem") & (S["model"] == "ENR")].iloc[0]
L += ["", "## Hypotheses", "",
      f"- **X1** (any cell: R² > 0, selection-corrected p < 0.05): best cell {best.cell}, R² {f(best.R2)}, r {f(best.r)}, "
      f"selection-corrected p = {f(best.p_selection_corrected)} → " +
      ("**supported**" if best.R2 > 0 and best.p_selection_corrected < 0.05 else "**not supported**"),
      f"- **X2** (pre-specified F-riem × riem × MC on × ENR): R² {f(fp.R2)}, r {f(fp.r)}, MAE {f(fp.MAE)}, uncorrected p = "
      f"{f(fp.p_uncorrected)} → " + ("**supported**" if fp.R2 > 0 and fp.p_uncorrected < 0.05 else "**not supported**"),
      "- **X3** (descriptive): mismatch-compression screen off → on, raw pooled R² / r, per family × alignment × model:", "",
      "| Family | Alignment | Model | off R² | off r | on R² | on r |", "|---|---|---|---|---|---|---|"]
piv = S.set_index(["family", "align", "model", "mc"])
for fam, al, m in S[["family", "align", "model"]].drop_duplicates().values:
    a, b = piv.loc[(fam, al, m, False)], piv.loc[(fam, al, m, True)]
    L.append(f"| {fam} | {al} | {m} | {f(a.R2)} | {f(a.r)} | {f(b.R2)} | {f(b.r)} |")
L += ["", f"- **X4** (descriptive): calibration curve for the best cell ({C.cell.iloc[0]}), raw:", "",
      "| Calibration weeks N | R² | r | MAE |", "|---|---|---|---|"]
L += [f"| {int(r.N)} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} |" for r in C.sort_values("N").itertuples()]
cnt = D.assign(feat=D.dropped.fillna("").str.split(";")).explode("feat")
cnt = cnt[cnt.feat != ""].groupby("feat").held_out.nunique().sort_values(ascending=False)
L += ["", "## Mismatch-compression feature screen", "",
      "Features dropped in at least one leave-one-patient-out fold (number of folds, of 6):", ""]
L += [f"- `{k}`: {v}" for k, v in cnt.items()] or ["- none"]
L += ["", "<!-- ai-end -->", ""]

# ---------------------------------------------------------------- phase 2 (amendment P2)
if (O / "p2_lopo_null.csv").exists():
    P2 = pd.read_csv(O / "p2_lopo_scores.csv")
    N2 = pd.read_csv(O / "p2_lopo_null.csv")
    LC = pd.read_csv(O / "p2_lds_causal_scores.csv")
    m2 = N2.groupby("draw").R2.max()
    comb = pd.concat([N.groupby("draw").R2.max(), m2], axis=1).max(axis=1)
    P2["p_phase2"] = [(np.sum(m2 >= r) + 1) / (len(m2) + 1) for r in P2.R2]
    P2["p_combined"] = [(np.sum(comb >= r) + 1) / (len(comb) + 1) for r in P2.R2]
    P2.to_csv(O / "p2_lopo_scores_with_p.csv", index=False)
    L += ["## Phase 2 (amendment P2): metric pullback, stitched LDS, Gromov–Wasserstein", "", "<!-- ai-start -->",
          "Calibration-free leave-one-patient-out, mismatch-compression screen on, label-free alignment per family. Raw values.",
          f"Reference predictors (MC on): training mean R² {f(R[(R.mc == True) & (R.model == 'REF_train_mean')].R2.iloc[0])}, "
          f"r {f(R[(R.mc == True) & (R.model == 'REF_train_mean')].r.iloc[0])}; time-only R² "
          f"{f(R[(R.mc == True) & (R.model == 'REF_time')].R2.iloc[0])}, r {f(R[(R.mc == True) & (R.model == 'REF_time')].r.iloc[0])}.",
          f"Null best-of-15 R² (phase 2): mean {f(m2.mean())}, 95th pct {f(m2.quantile(0.95))}; best-of-103 (phase 1 + 2): "
          f"mean {f(comb.mean())}, 95th pct {f(comb.quantile(0.95))}.", "",
          "| Family | Method | R² | r | MAE | p (phase 2) | p (phase 1 + 2) | " + " | ".join(f"R² {p}" for p in PTS) + " |",
          "|---|---|---|---|---|---|---|" + "---|" * len(PTS)]
    for r in P2.sort_values("R2", ascending=False).itertuples():
        L.append(f"| {r.family} | {r.method} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} | {f(r.p_phase2)} | {f(r.p_combined)} | "
                 + " | ".join(f(getattr(r, f'R2_{p}'), 2) for p in PTS) + " |")
    b2 = P2.sort_values("R2", ascending=False).iloc[0]
    L += ["", f"- **X5** (phase 2, selection-corrected within phase 2): best {b2.family} × {b2.method}, R² {f(b2.R2)}, r {f(b2.r)}, "
          f"p = {f(b2.p_phase2)} → " + ("**supported**" if b2.R2 > 0 and b2.p_phase2 < 0.05 else "**not supported**"),
          f"- **X6** (combined phase 1 + 2 family): best phase-2 cell p = {f(b2.p_combined)} → "
          + ("**supported**" if b2.R2 > 0 and b2.p_combined < 0.05 else "**not supported**"),
          "", "Stitched LDS, causal (Kalman filter) predictions, descriptive:", "",
          "| Family | R² | r | MAE |", "|---|---|---|---|"]
    L += [f"| {r.family} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} |" for r in LC.itertuples()]
    if (O / "p2_cebra_scores.csv").exists():
        CE = pd.read_csv(O / "p2_cebra_scores.csv")
        CN = pd.read_csv(O / "p2_cebra_null.csv") if (O / "p2_cebra_null.csv").exists() else None
        L += ["", "**P2-C CEBRA-Behavior (exploratory; 20-draw uncorrected null)**", "",
              "| Family | R² | r | MAE | cross-patient consistency | p (this cell, 20 draws) | " + " | ".join(f"R² {p}" for p in PTS) + " |",
              "|---|---|---|---|---|---|" + "---|" * len(PTS)]
        for r in CE.itertuples():
            pv = (np.sum(CN[CN.family == r.family].R2 >= r.R2) + 1) / (CN[CN.family == r.family].R2.notna().sum() + 1) if CN is not None else np.nan
            L.append(f"| {r.family} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} | {f(r.consistency_mean)} | {f(pv)} | "
                     + " | ".join(f(getattr(r, f'R2_{p}'), 2) for p in PTS) + " |")
        if (O / "p2_cebra_scores_run1.csv").exists():
            r1 = pd.read_csv(O / "p2_cebra_scores_run1.csv").set_index("family")
            L += ["", "CEBRA training is not bit-deterministic here (its internal sampling isn't controlled by the torch seed).",
                  "Run 1 (used for the 20-draw null; consistency failed with the default 100 label bins) versus run 2 (table above; 10 bins):", "",
                  "| Family | run 1 R² | run 1 r | run 2 R² | run 2 r |", "|---|---|---|---|---|"]
            L += [f"| {r.family} | {f(r1.loc[r.family, 'R2'])} | {f(r1.loc[r.family, 'r'])} | {f(r.R2)} | {f(r.r)} |" for r in CE.itertuples()]
        L += ["", "- **X7** (descriptive): CEBRA embeddings are moderately consistent across training patients (about 0.46–0.53), "
              "but no input gives positive leave-one-patient-out R² in either run."]
    L += ["<!-- ai-end -->", ""]

# ---------------------------------------------------------------- amendment P3: FOOOF-based families
if (O / "p3_lopo_null.csv").exists():
    P3 = pd.read_csv(O / "p3_lopo_scores.csv")
    N3 = pd.read_csv(O / "p3_lopo_null.csv")
    C3 = pd.read_csv(O / "p3_calibration.csv")
    D3 = pd.read_csv(O / "p3_mc_screen_dropped.csv")
    lab = lambda mc, fa, al, m: f"{'MC' if mc else 'noMC'} | {fa} | {al} | {m}"
    P3["cell"] = [lab(*v) for v in P3[["mc", "family", "align", "model"]].values]
    m3 = N3.groupby("draw").R2.max()
    parts = [N.groupby("draw").R2.max(), m3]
    if (O / "p2_lopo_null.csv").exists():
        parts.append(pd.read_csv(O / "p2_lopo_null.csv").groupby("draw").R2.max())
    comb3 = pd.concat(parts, axis=1).max(axis=1)
    P3["p_P3"] = [(np.sum(m3 >= r) + 1) / (len(m3) + 1) for r in P3.R2]
    P3["p_combined"] = [(np.sum(comb3 >= r) + 1) / (len(comb3) + 1) for r in P3.R2]
    P3["p_cell"] = [(np.sum(N3[N3.cell == c].R2 >= r) + 1) / (N3[N3.cell == c].R2.notna().sum() + 1) for c, r in zip(P3.cell, P3.R2)]
    P3.to_csv(O / "p3_lopo_scores_with_p.csv", index=False)
    x8 = P3[P3.cell == "noMC | F-fooof-full | z | ENR+time"].iloc[0]
    b3 = P3.sort_values("R2", ascending=False).iloc[0]
    rm = R[R.mc == False].set_index("model")
    L += ["## Amendment P3: FOOOF-based families, calibration-free leave-one-patient-out", "", "<!-- ai-start -->",
          f"Reference predictors (raw): training mean R² {f(rm.loc['REF_train_mean','R2'])}, r {f(rm.loc['REF_train_mean','r'])}; "
          f"time-only R² {f(rm.loc['REF_time','R2'])}, r {f(rm.loc['REF_time','r'])}.",
          f"Null best-of-108 R² (P3): mean {f(m3.mean())}, 95th pct {f(m3.quantile(0.95))}; best over phase 1 + 2 + P3 ({len(parts)} families): "
          f"mean {f(comb3.mean())}, 95th pct {f(comb3.quantile(0.95))}.", "",
          f"- **X8** (forward-chaining winner config, F-fooof-full × z × MC off × ENR+time): R² {f(x8.R2)}, r {f(x8.r)}, MAE {f(x8.MAE)}, "
          f"uncorrected p = {f(x8.p_cell)} → " + ("**supported**" if x8.R2 > 0 and x8.p_cell < 0.05 else "**not supported**"),
          f"- **X9** (any P3 cell, corrected within P3): best {b3.cell}, R² {f(b3.R2)}, r {f(b3.r)}, p = {f(b3.p_P3)} → "
          + ("**supported**" if b3.R2 > 0 and b3.p_P3 < 0.05 else "**not supported**"),
          f"- **X10** (combined phase 1 + 2 + P3): best P3 cell p = {f(b3.p_combined)} → "
          + ("**supported**" if b3.R2 > 0 and b3.p_combined < 0.05 else "**not supported**"), "",
          "| MC | Family | Alignment | Model | R² | r | MAE | p (this cell) | p (P3) | p (combined) | " + " | ".join(f"R² {p}" for p in PTS) + " |",
          "|---|---|---|---|---|---|---|---|---|---|" + "---|" * len(PTS)]
    for r in P3.sort_values("R2", ascending=False).itertuples():
        L.append(f"| {'on' if r.mc else 'off'} | {r.family} | {r.align} | {r.model} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} | "
                 f"{f(r.p_cell)} | {f(r.p_P3)} | {f(r.p_combined)} | " + " | ".join(f(getattr(r, f'R2_{p}'), 2) for p in PTS) + " |")
    L += ["", "**X11** calibration curves (raw):", "", "| Cell | N | R² | r | MAE |", "|---|---|---|---|---|"]
    L += [f"| {r.cell} | {int(r.N)} | {f(r.R2)} | {f(r.r)} | {f(r.MAE)} |" for r in C3.sort_values(["cell", "N"]).itertuples()]
    c3 = D3.assign(feat=D3.dropped.fillna("").str.split(";")).explode("feat")
    c3 = c3[c3.feat != ""].groupby("feat").held_out.nunique().sort_values(ascending=False)
    L += ["", "Mismatch-compression screen, FOOOF features dropped (folds of 6):", ""]
    L += [f"- `{k}`: {v}" for k, v in c3.items()] or ["- none"]
    L += ["<!-- ai-end -->", ""]

(HERE / "RESULTS.md").write_text("\n".join(L))
print("\n".join(L[:14]))
